package kr.or.fact.api.model.DTO;

import lombok.Data;

import java.util.Date;

@Data
public class VerifyDataSensorTestVO {
    long idx_verdata_sensortest;// number(10,4) PRIMARY KEY,
    String verifyid;//  varchar(100),
    String deviceid;// varchar(100),
    String daqtime;//  date ,
    double temp;// number(10,4),
    double hum;// number(10,4),
    double value1;// number(10,4),
    double value2;// number(10,4),
    double value3;// number(10,4),
    double value4;// number(10,4),
    double value5;// number(10,4),
    double value6;// number(10,4),
    double value7;// number(10,4),
    double value8;// number(10,4),
    double value9;// number(10,4),
    double value10;// number(10,4),
    double value11;// number(10,4),
    double value12;// number(10,4),
    int divalue1;// int,
    int divalue2;// int,
    int divalue3;// int,
    int divalue4;// int,
    int dovalue1;// int,
    int dovalue2;// int,
    int aovalue1;// int,
    int aovalue2;// int,
    String valuename1;// varchar(100),
    String valuename2;// varchar(100),
    String valuename3;// varchar(100),
    String valuename4;// varchar(100),
    String valuename5;// varchar(100),
    String valuename6;// varchar(100),
    String valuename7;// varchar(100),
    String valuename8;// varchar(100),
    String valuename9;// varchar(100),
    String valuename10;// varchar(100),
    String valuename11;// varchar(100),
    String valuename12;// varchar(100),
    String valueunit1;// varchar(100),
    String valueunit2;// varchar(100),
    String valueunit3;// varchar(100),
    String valueunit4;// varchar(100),
    String valueunit5;// varchar(100),
    String valueunit6;// varchar(100),
    String valueunit7;// varchar(100),
    String valueunit8;// varchar(100),
    String valueunit9;// varchar(100),
    String valueunit10;// varchar(100),
    String valueunit11;// varchar(100),
    String valueunit12;// varchar(100),
    String divaluename1;// varchar(100),
    String divaluename2;// varchar(100),
    String divaluename3;// varchar(100),
    String divaluename4;// varchar(100),
    String dovaluename1;// varchar(100),
    String dovaluename2;// varchar(100),
    String aovaluename1;// varchar(100),
    String aovaluename2;// varchar(100),
    String aovalueunit1;// varchar(100),
    String aovalueunit2;// varchar(100)
    String username;
    String key;
}
