package kr.or.fact.api.model.DTO;

import lombok.Data;

import java.util.Date;

@Data
public class VerifyDataHeatFlowVO {
    long idx_verdata_heatflow;// number(10,4) PRIMARY KEY,
    String verifyid;//  varchar(100),
    String deviceid;// varchar(100),
    String daqtime;//  date ,
    double temp_a_main;// number(10,4),
    double hum_a;// number(10,4),
    double temp_a_hotbox_main;// number(10,4),
    double windspeed_a_hotbox;// number(10,4),
    double volt_a_hotbox_heater;// number(10,4),
    double amp_a_hotbox_heater;// number(10,4),
    double volt_a_hotbox_fan;// number(10,4),
    double amp_a_hotbox_fan;// number(10,4),
    double temp_b_main;// number(10,4),
    double windspeed_b_coolingbox;// number(10,4),
    double temp_a_sub1;// number(10,4),
    double temp_a_sub2;// number(10,4),
    double temp_a_sub3;// number(10,4),
    double temp_a_sub4;// number(10,4),
    double temp_a_sub5;// number(10,4),
    double temp_a_sub6;// number(10,4),
    double temp_a_sub7;// number(10,4),
    double temp_a_sub8;// number(10,4),
    double temp_a_sub9;// number(10,4),
    double temp_a_sub10;// number(10,4),
    double temp_a_sub11;// number(10,4),
    double temp_a_sub12;// number(10,4),
    double temp_a_sub13;// number(10,4),
    double temp_a_sub14;// number(10,4),
    double temp_a_sub15;// number(10,4),
    double temp_a_sub16;// number(10,4),
    double temp_a_sub17;// number(10,4),
    double temp_a_sub18;// number(10,4),
    double temp_a_sub19;// number(10,4),
    double temp_a_sub20;// number(10,4),
    double temp_a_sub21;// number(10,4),
    double temp_a_sub22;// number(10,4),
    double temp_a_sub23;// number(10,4),
    double temp_a_sub24;// number(10,4),
    double temp_a_sub25;// number(10,4),
    double temp_a_sub26;// number(10,4),
    double temp_a_sub27;// number(10,4),
    double temp_a_sub28;// number(10,4),
    double temp_a_sub29;// number(10,4),
    double temp_a_sub30;// number(10,4),
    double temp_a_hotbox_sub1;// number(10,4),
    double temp_a_hotbox_sub2;// number(10,4),
    double temp_a_hotbox_sub3;// number(10,4),
    double temp_a_hotbox_sub4;// number(10,4),
    double temp_a_hotbox_sub5;// number(10,4),
    double temp_a_hotbox_sub6;// number(10,4),
    double temp_a_hotbox_sub7;// number(10,4),
    double temp_a_hotbox_sub8;// number(10,4),
    double temp_a_hotbox_sub9;// number(10,4),
    double temp_a_hotbox_sub10;// number(10,4),
    double temp_a_hotbox_sub11;// number(10,4),
    double temp_a_hotbox_sub12;// number(10,4),
    double temp_a_hotbox_sub13;// number(10,4),
    double temp_a_hotbox_sub14;// number(10,4),
    double temp_a_hotbox_sub15;// number(10,4),
    double temp_a_hotbox_sub16;// number(10,4),
    double temp_a_hotbox_sub17;// number(10,4),
    double temp_a_hotbox_sub18;// number(10,4),
    double temp_a_hotbox_sub19;// number(10,4),
    double temp_a_hotbox_sub20;// number(10,4),
    double temp_a_hotbox_sub21;// number(10,4),
    double temp_a_hotbox_sub22;// number(10,4),
    double temp_a_hotbox_sub23;// number(10,4),
    double temp_a_hotbox_sub24;// number(10,4),
    double temp_a_hotbox_sub25;// number(10,4),
    double temp_a_hotbox_sub26;// number(10,4),
    double temp_a_hotbox_sub27;// number(10,4),
    double temp_a_hotbox_sub28;// number(10,4),
    double temp_a_hotbox_sub29;// number(10,4),
    double temp_a_hotbox_sub30;// number(10,4),
    double temp_b_sub1;// number(10,4),
    double temp_b_sub2;// number(10,4),
    double temp_b_sub3;// number(10,4),
    double temp_b_sub4;// number(10,4),
    double temp_b_sub5;// number(10,4),
    double temp_b_sub6;// number(10,4),
    double temp_b_sub7;// number(10,4),
    double temp_b_sub8;// number(10,4),
    double temp_b_sub9;// number(10,4),
    double temp_b_sub10;// number(10,4),
    double temp_b_sub11;// number(10,4),
    double temp_b_sub12;// number(10,4),
    double temp_b_sub13;// number(10,4),
    double temp_b_sub14;// number(10,4),
    double temp_b_sub15;// number(10,4),
    double temp_b_sub16;// number(10,4),
    double temp_b_sub17;// number(10,4),
    double temp_b_sub18;// number(10,4),
    double temp_b_sub19;// number(10,4),
    double temp_b_sub20;// number(10,4),
    double temp_b_sub21;// number(10,4),
    double temp_b_sub22;// number(10,4),
    double temp_b_sub23;// number(10,4),
    double temp_b_sub24;// number(10,4),
    double temp_b_sub25;// number(10,4),
    double temp_b_sub26;// number(10,4),
    double temp_b_sub27;// number(10,4),
    double temp_b_sub28;// number(10,4),
    double temp_b_sub29;// number(10,4),
    double temp_b_sub30;// number(10,4)
    String username;
    String key;
}
