CREATE DATABASE
    USER sys IDENTIFIED BY tibero
    MAXDATAFILES 512
    CHARACTER SET UTF8 -- UTF8, EUCKR, ASCII ...
    NATIONAL CHARACTER SET UTF8
    LOGFILE
        GROUP 0 '/data2/tbdata/fact_log01.log' SIZE 100M,
        GROUP 1 '/data2/tbdata/fact_log11.log' SIZE 100M,
        GROUP 2 '/data2/tbdata/fact_log21.log' SIZE 100M
    MAXLOGFILES 100
    MAXLOGMEMBERS 2
    NOARCHIVELOG
    DATAFILE '/data2/tbdata/fact_data.dtf' SIZE 1000M
    AUTOEXTEND ON NEXT 256M MAXSIZE 100G
    DEFAULT TEMPORARY TABLESPACE TEMP
    TEMPFILE '/data2/tbdata/fact_temp001.dtf' SIZE 1000M
    AUTOEXTEND ON NEXT 64M MAXSIZE 10G
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE
    UNDO TABLESPACE UNDO
    DATAFILE '/data2/tbdat'



CREATE DATABASE
    USER sys IDENTIFIED BY tibero
    MAXDATAFILES 512
    CHARACTER SET UTF8 -- UTF8, EUCKR, ASCII ...
    NATIONAL CHARACTER SET UTF8
    LOGFILE
GROUP 0 '/data2/tbdata/fact_log01.log' SIZE 100M,
GROUP 1 '/data2/tbdata/fact_log11.log' SIZE 100M,
GROUP 2 '/data2/tbdata/fact_log21.log' SIZE 100M
MAXLOGFILES 100
MAXLOGMEMBERS 2
NOARCHIVELOG
DATAFILE '/data2/tbdata/fact_data.dtf' SIZE 1000M
AUTOEXTEND ON NEXT 256M MAXSIZE 100G
DEFAULT TEMPORARY TABLESPACE TEMP
TEMPFILE '/data2/tbdata/fact_temp001.dtf' SIZE 1000M
AUTOEXTEND ON NEXT 64M MAXSIZE 10G
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
UNDO TABLESPACE UNDO
DATAFILE '/data2/tbdata/fact_undo001.dtf' SIZE 200M
AUTOEXTEND ON NEXT 64M MAXSIZE 10G
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 128k
DEFAULT TABLESPACE USR
DATAFILE '/data2/tbdata/fact_usr001.dtf' SIZE 50m
AUTOEXTEND ON NEXT 64m MAXSIZE 3G
SYSSUB
DATAFILE '/data2/tbdata/fact_syssub001.dtf' SIZE 50m
AUTOEXTEND ON NEXT 64M MAXSIZE 3G ;




/*1*/
CREATE TABLE TB_CORP_INFO
(
    IDX_CORP_INFO	NUMBER(32) NOT NULL,
    CORP_NAME_KOR	VARCHAR2(100),
    COMPANY_NUM	VARCHAR2(20),
    CORP_REG_NUM	VARCHAR2(20),
    TEL_NUM	VARCHAR2(20),
    FAX_NUM	VARCHAR2(20),
    EMAIL	VARCHAR2(320),
    HOMEPAGE	VARCHAR2(255),
    CORP_ADDR	VARCHAR2(200),
    IS_OTHER_ADDR	NUMBER(4) DEFAULT 0,
    OTHER_ADDR	VARCHAR2(200),
    SALES_IN_PREV	NUMBER(38),
    CA_RATIO	NUMBER(4),
    EMPLOEE_NUM	NUMBER(10),
    BS_SECTOR	VARCHAR2(100),
    PRODUCT	VARCHAR2(100),
    BS_PLAN	VARCHAR2(100),
    DEMO_FACILITY_TYPE	NUMBER(4) DEFAULT 0,
    DEMO_FACILITY_ETC	VARCHAR2(20),
    FOUNDING_DATE	DATE,
    CEO_NAME_KOR	VARCHAR2(40),
    CEO_ADDR	VARCHAR2(200),
    CEO_TEL_NUM	VARCHAR2(20),
    CEO_MPHONE_NUM	VARCHAR2(20),
    CEO_EMAIL	VARCHAR2(320),
    REG_DATE	DATE,
    LAST_UPD_DATE	DATE,
    CONSTRAINT CORP_INFO_PK PRIMARY KEY (IDX_CORP_INFO)
)
    LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE SEQUENCE SEQ_CORP_INFO INCREMENT BY 1 START WITH 10000;

/*2*/
CREATE TABLE TB_CORP_CEO
(
    IDX_CORP_CEO	NUMBER(32) NOT NULL,
    CEO_NAME_KOR	VARCHAR2(40),
    CEO_ADDR	VARCHAR2(200),
    CEO_TEL_NUM	VARCHAR2(20),
    CEO_MPHONE_NUM	VARCHAR2(20),
    CEO_EMAIL	VARCHAR2(320),
    REG_DATE	DATE,
    LAST_UPD_DATE	DATE,
    IDX_CORP_INFO	NUMBER(32) DEFAULT 0,
    CONSTRAINT CORP_CEO_PK PRIMARY KEY (IDX_CORP_CEO)
)
    LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE SEQUENCE SEQ_CORP_CEO INCREMENT BY 1 START WITH 10000;


/*3*/
CREATE TABLE TB_CORP_MANAGER
(
    IDX_CORP_MANAGER	NUMBER(32) NOT NULL,
    MANAGER_NAME_KOR	VARCHAR2(40),
    CORP_MANAGER_TYPE	NUMBER(4),
    DEPARTMENT	VARCHAR2(40),
    JOB_TITLE	VARCHAR2(40),
    TEL_NUM	VARCHAR2(20),
    MPHONE_NUM	VARCHAR2(20),
    EMAIL	VARCHAR2(320),
    REG_DATE	DATE,
    LAST_UPD_DATE	DATE,
    IDX_CORP_INFO	NUMBER(32) DEFAULT 0,
    IDX_USER	NUMBER(32) DEFAULT 0,
    CONSTRAINT CORP_MANAGER_PK PRIMARY KEY (IDX_CORP_MANAGER)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_CORP_MANAGER INCREMENT BY 1 START WITH 10000;

/*4*/
CREATE TABLE TB_USER_DEMO_BS_PLAN
(
    IDX_USER_DEMO_BS_PLAN	NUMBER(32) NOT NULL,
    IDX_DEMO_BUSINESS	NUMBER(32) DEFAULT 0,
    DEMO_PLAN_TYPE	NUMBER(4),
    DEMO_FACILITY	NUMBER(4),
    DEMO_WAY	NUMBER(4),
    DEMO_REPEAT	NUMBER(4),
    DEMO_GOAL	NUMBER(4),
    DEMO_OPTION	NUMBER(4),
    DEMO_CROPS	VARCHAR2(100),
    CULTURE_SOIL	NUMBER(4),
    DEMO_TYPE	NUMBER(4),
    DEMO_START_DATE	DATE,
    DEMO_END_DATE	DATE,
    RESIDENT_TYPE	NUMBER(4),
    STAFF_NUM	NUMBER(10),
    USAGE_FEE	NUMBER(20),
    DEPOSIT	NUMBER(20),
    IS_CHANGE	NUMBER(4),
    IS_CONFIRM	NUMBER(4),
    IS_SHARE	NUMBER(4),
    IS_FEE_FILE	NUMBER(4),
    IS_CONFIRM_FILE	NUMBER(4),
    IS_CONTRACT_INFO_FILE NUMBER(4),
    REG_DATE	DATE,
    LAST_UPD_DATE	DATE,
    IDX_CORP_INFO	NUMBER(32) DEFAULT 0,
    IDX_USER	NUMBER(32) DEFAULT 0,
    CONSTRAINT USER_DEMO_BS_PLAN_PK PRIMARY KEY (IDX_USER_DEMO_BS_PLAN)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_USER_DEMO_BS_PLAN INCREMENT BY 1 START WITH 10000;

/*5*/
CREATE TABLE TB_FILE_INFO
(
    IDX_FILE_INFO	NUMBER(32) NOT NULL,
    FILE_NAME	VARCHAR2(256),
    FILE_TYPE	NUMBER(4),
    FILE_STATUS	NUMBER(4),
    MIME_TYPE	VARCHAR2(100),
    ENCODING	NUMBER(4),
    EXTENTION	VARCHAR2(20),
    FILE_SECURE_TYPE	NUMBER(4),
    FILE_PATH	VARCHAR2(256),
    FILE_SIZE	NUMBER(32) DEFAULT 0,
    CHECKSUM	NUMBER(20),
    OWNER	NUMBER(4),
    IDX_USER	NUMBER(32) DEFAULT 0,
    IDX_ADMIN	NUMBER(32) DEFAULT 0,
    REG_DATE	DATE,
    CONSTRAINT FILE_INFO_PK PRIMARY KEY (IDX_FILE_INFO)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_FILE_INFO INCREMENT BY 1 START WITH 10000;

/*6*/
CREATE TABLE TB_USER_DEMO_BS_PLAN_FILE_JOIN
(
    IDX_USER_DEMO_BS_PLAN_FILE_JOIN	NUMBER(32) NOT NULL,
    JOIN_TYPE	NUMBER(4),
    IDX_USER_DEMO_BS_PLAN	NUMBER(32) DEFAULT 0,
    FILE_VERION	NUMBER(4),
    IS_LAST	NUMBER(4),
    IDX_FILE_INFO	NUMBER(32) DEFAULT 0,
    REG_DATE	DATE,
    CONSTRAINT USER_DEMO_BS_PLAN_FILE_JOIN_PK PRIMARY KEY (IDX_USER_DEMO_BS_PLAN_FILE_JOIN)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_USER_DEMO_BS_PLAN_FILE_JOIN INCREMENT BY 1 START WITH 10000;

/*7*/
CREATE TABLE TB_USER_DEMO_BS_PROGRESS
(
    IDX_USER_DEMO_BS_PROGRESS	NUMBER(32) NOT NULL,
    IDX_USER_DEMO_BS	NUMBER(32) DEFAULT 0,
    TOTAL_PROGRESS	NUMBER(6,2),
    PROGRESS_STATUS	NUMBER(4),
    PROGRESS_OWNER	VARCHAR2(100),
    IDX_CORP_INFO	NUMBER(32) DEFAULT 0,
    REG_DATE	DATE,
    CONSTRAINT USER_DEMO_BS_PROGRESS_PK PRIMARY KEY (IDX_USER_DEMO_BS_PROGRESS)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_USER_DEMO_BS_PROGRESS INCREMENT BY 1 START WITH 10000;

/*8*/
CREATE TABLE TB_USER_DEMO_BS_PROGRESS_STEP
(
    IDX_USER_DEMO_BS_PROGRESS_STEP	NUMBER(32) NOT NULL,
    IDX_USER_DEMO_BS_PROGRESS	NUMBER(32) DEFAULT 0,
    STEP_NAME	VARCHAR2(100),
    STEP_STATUS	NUMBER(4),
    STEP_ORDER	NUMBER(4),
    REG_DATE	DATE,
    CONSTRAINT USER_DEMO_BS_PROGRESS_STEP_PK PRIMARY KEY (IDX_USER_DEMO_BS_PROGRESS_STEP)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_USER_DEMO_BS_PROGRESS_STEP INCREMENT BY 1 START WITH 10000;

/*9*/
CREATE TABLE TB_USER_DEMO_BS_PROGRESS_ITEM
(
    IDX_USER_DEMO_BS_PROGRESS_ITEM	NUMBER(32) NOT NULL,
    STEP_ITEM_NAME	VARCHAR2(100),
    STEP_ITEM_ORDER	NUMBER(4),
    PROGRESS_RATE	NUMBER(6,2),
    START_DATE	DATE,
    END_DATE	DATE,
    IDX_USER_DEMO_BS_PROGRESS_STEP	NUMBER(32) DEFAULT 0,
    REG_DATE	DATE,
    CONSTRAINT USER_DEMO_BS_PROGRESS_ITEM_PK PRIMARY KEY (IDX_USER_DEMO_BS_PROGRESS_ITEM)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_USER_DEMO_BS_PROGRESS_ITEM INCREMENT BY 1 START WITH 10000;

/*10*/
CREATE TABLE TB_USAGE_FEE
(
    IDX_USAGE_FEE	NUMBER(32) NOT NULL,
    USAGE_FEE_NAME	VARCHAR2(100),
    FEE_ORDER	NUMBER(4),
    MAIN_NAME	VARCHAR2(100),
    SUB_NAME	VARCHAR2(100),
    FEE_MEMO	VARCHAR2(100),
    FEE_TYPE	NUMBER(4),
    AREA_SIZE	NUMBER(20),
    FEE_RATE	NUMBER(20),
    USAGE_COUNT	NUMBER(20),
    USAGE_FEE	NUMBER(32) DEFAULT 0,
    START_DATE	DATE,
    END_DATE	DATE,
    IDX_CORP_INFO	NUMBER(32) DEFAULT 0,
    IDX_USER_DEMO_BS	NUMBER(32) DEFAULT 0,
    REG_DATE	DATE,
    CONSTRAINT USAGE_FEE_PK PRIMARY KEY (IDX_USAGE_FEE)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_USAGE_FEE INCREMENT BY 1 START WITH 10000;

/*11*/
CREATE TABLE TB_BS_ANNOUNCEMENT
(
    IDX_BS_ANNOUNCEMENT	NUMBER(32),
    BS_ANNOUNCEMENT_CODE	VARCHAR2(40),
    ANNOUNCE_NUM NUMBER(20),
    SUBJECT	VARCHAR2(100),
    ANNOUNCE_CONTENTS	CLOB,
    BS_STATUS	NUMBER(4) DEFAULT 0,
    IS_FILE NUMBER(4) DEFAULT 0,
    IS_NEW	NUMBER(4) DEFAULT 0,
    IS_MAIN_PAGE	NUMBER(4) DEFAULT 0,
    IS_IMPORTANT	NUMBER(4) DEFAULT 0,
    IS_SHOW	NUMBER(4) DEFAULT 0,
    VIEW_COUNT	NUMBER(20),
    ANNOUNCE_STATUS	NUMBER(4) DEFAULT 0,
    POSTING_START_DATE	DATE,
    POSTING_END_DATE	DATE,
    DOC_VERSION	NUMBER(4) DEFAULT 1,
    MEMO	VARCHAR2(1000),
    SEARCH_TAG	NUMBER(32),
    AUTHOR	VARCHAR2(20),
    IDX_DEMO_BUSINESS	NUMBER(32),
    CONFIRM_ADMIN_IDX	NUMBER(32),
    IDX_ADMIN	NUMBER(32),
    REG_DATE	DATE,
    LAST_UPD_DATE	DATE,
    CONSTRAINT BS_ANNOUNCEMENT_PK PRIMARY KEY (IDX_BS_ANNOUNCEMENT)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_BS_ANNOUNCEMENT INCREMENT BY 1 START WITH 10000;

/*12*/
CREATE TABLE TB_DEMO_BUSINESS
(
    IDX_DEMO_BUSINESS	NUMBER(32) NOT NULL,
    DEMO_BS_CODE	VARCHAR2(40),
    DEMO_SUBJECT	VARCHAR2(100),
    DEMO_BS_CONTENTS	VARCHAR2(3000),
    DEMO_BS_MAIN_TYPE	VARCHAR2(40),
    DEMO_BS_SUB_TYPE	VARCHAR2(40),
    DEMO_BS_DETAIL_TYPE	VARCHAR2(40),
    DEMO_BS_STATUS	NUMBER(4),
    APPLICANT_COUNT	NUMBER(10),
    APPLICANT_COUNT_LIMIT	NUMBER(4),
    START_DATE	DATE,
    END_DATE	DATE,
    RECRUIT_START_DATE	DATE,
    RECRUIT_END_DATE	DATE,
    RECRUIT_COUNT_LIMIT	NUMBER(10),
    MEMO	VARCHAR2(1000),
    IDX_ADMIN	NUMBER(32) DEFAULT 0,
    IDX_CONFORM_ADMIN NUMBER(32) DEFAULT 0,
    IS_ANNOUNCE NUMBER(4) DEFAULT 0,
    REG_DATE	DATE,
    LAST_UPD_DATE	DATE,
    CONSTRAINT DEMO_BUSINESS_PK PRIMARY KEY (IDX_DEMO_BUSINESS)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_DEMO_BUSINESS INCREMENT BY 1 START WITH 10000;

/*13*/
CREATE TABLE TB_DEMO_BS_APPLICAION
(
    IDX_DEMO_BS_APPLICAION	NUMBER(32) NOT NULL,
    DEMO_BS_APPLICAION_CODE	VARCHAR2(40),
    IDX_DEMO_BUSINESS	NUMBER(32) DEFAULT 0,
    IDX_CORP_INFO	NUMBER(32) DEFAULT 0,
    APPLICANT_STATUS	NUMBER(4),
    DEMO_PLAN_TYPE	NUMBER(4),
    IS_FILE	NUMBER(4),
    IS_IMPROVE	NUMBER(4),
    IS_IMPROVE_FILE	NUMBER(4),
    APPLICAION_REG_DATE	DATE,
    IMPROVE_RECOMM_DATE	DATE,
    MEMO	VARCHAR2(1000),
    IDX_ADMIN	NUMBER(32) DEFAULT 0,
    REG_DATE	DATE,
    CONSTRAINT DEMO_BS_APPLICAION_PK PRIMARY KEY (IDX_DEMO_BS_APPLICAION)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_DEMO_BS_APPLICAION INCREMENT BY 1 START WITH 10000;

/*14*/
CREATE TABLE TB_DEMO_BS_APPLICAION_FILE_JOIN
(
    IDX_DEMO_BS_APPLICAION_FILE_JOIN	NUMBER(32) NOT NULL,
    IDX_DEMO_BS_APPLICAION	NUMBER(32) DEFAULT 0,
    IDX_DEMO_BUSINESS	NUMBER(32) DEFAULT 0,
    FILE_VERION	NUMBER(4),
    IS_LAST	NUMBER(4),
    IDX_FILE_INFO	NUMBER(32) DEFAULT 0,
    IDX_ADMIN	NUMBER(32) DEFAULT 0,
    REG_DATE	DATE,
    CONSTRAINT DEMO_BS_APPLICAION_FILE_JOIN_PK PRIMARY KEY (IDX_DEMO_BS_APPLICAION_FILE_JOIN)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_DEMO_BS_APPLICAION_FILE_JOIN INCREMENT BY 1 START WITH 10000;

/*15*/
CREATE TABLE TB_DEMO_BS_APPLICAION_EVALUATE
(
    IDX_DEMO_BS_APPLICAION_EVALUATE	NUMBER(32) NOT NULL,
    IDX_DEMO_BS_APPLICAION	NUMBER(32) DEFAULT 0,
    IDX_DEMO_BUSINESS	NUMBER(32) DEFAULT 0,
    IDX_CORP_INFO	NUMBER(32) DEFAULT 0,
    EVALUATE_TYPE	NUMBER(4),
    EVALUATE_STATUS	NUMBER(4),
    IS_EVALUATE_FILE	NUMBER(4),
    IS_RESULT_FILE	NUMBER(4),
    IS_CONSULTANT	NUMBER(4),
    IS_SHARE	NUMBER(4),
    MEMO	VARCHAR2(1000),
    IDX_ADMIN	NUMBER(32) DEFAULT 0,
    REG_DATE	DATE,
    CONSTRAINT DEMO_BS_APPLICAION_EVALUATE_PK PRIMARY KEY (IDX_DEMO_BS_APPLICAION_EVALUATE)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_DEMO_BS_APPLICAION_EVALUATE INCREMENT BY 1 START WITH 10000;

/*16*/
CREATE TABLE TB_DEMO_BS_EVALUATE_FILE_JOIN
(
    IDX_DEMO_BS_EVALUATE_FILE_JOIN	NUMBER(32) NOT NULL,
    IDX_DEMO_BS_APPLICAION	NUMBER(32) DEFAULT 0,
    IDX_DEMO_BUSINESS	NUMBER(32) DEFAULT 0,
    IDX_DEMO_BS_APPLICAION_EVALUATE	NUMBER(32) DEFAULT 0,
    FILE_TYPE	NUMBER(4),
    FILE_VERION	NUMBER(4),
    IS_LAST	NUMBER(4),
    IDX_FILE_INFO	NUMBER(32) DEFAULT 0,
    IDX_ADMIN	NUMBER(32) DEFAULT 0,
    REG_DATE	DATE,
    CONSTRAINT DEMO_BS_EVALUATE_FILE_JOIN_PK PRIMARY KEY (IDX_DEMO_BS_EVALUATE_FILE_JOIN)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_DEMO_BS_EVALUATE_FILE_JOIN INCREMENT BY 1 START WITH 10000;

/*17*/
CREATE TABLE TB_DEMO_BS_CONTRACT
(
    IDX_DEMO_BS_CONTRACT	NUMBER(32) NOT NULL,
    IDX_DEMO_BS_APPLICAION	NUMBER(32) DEFAULT 0,
    IDX_DEMO_BUSINESS	NUMBER(32) DEFAULT 0,
    IDX_CORP_INFO	NUMBER(32) DEFAULT 0,
    IDX_DEMO_BS_APPLICAION_EVALUATE	NUMBER(32) DEFAULT 0,
    CONTRACT_TYPE	NUMBER(4),
    CONTRACT_STATUS	NUMBER(4),
    IS_CONTRACT_FILE	NUMBER(4),
    IS_FULL_PAYMENT	NUMBER(4),
    IS_SHARE	NUMBER(4),
    DEADLINE_DATE	DATE,
    MEMO	VARCHAR2(1000),
    IDX_ADMIN	NUMBER(32) DEFAULT 0,
    REG_DATE	DATE,
    CONSTRAINT DEMO_BS_CONTRACT_PK PRIMARY KEY (IDX_DEMO_BS_CONTRACT)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_DEMO_BS_CONTRACT INCREMENT BY 1 START WITH 10000;

/*18*/
CREATE TABLE TB_DEMO_BS_CONTRACT_FILE_JOIN
(
    IDX_DEMO_BS_CONTRACT_FILE_JOIN	NUMBER(32) NOT NULL,
    IDX_DEMO_BS_APPLICAION	NUMBER(32) DEFAULT 0,
    IDX_DEMO_BUSINESS	NUMBER(32) DEFAULT 0,
    IDX_DEMO_BS_CONTRACT	NUMBER(32) DEFAULT 0,
    FILE_TYPE	NUMBER(4),
    FILE_VERION	NUMBER(4),
    IS_LAST	NUMBER(4),
    IDX_FILE_INFO	NUMBER(32) DEFAULT 0,
    IDX_ADMIN	NUMBER(32) DEFAULT 0,
    REG_DATE	DATE,
    CONSTRAINT DEMO_BS_CONTRACT_FILE_JOIN_PK PRIMARY KEY (IDX_DEMO_BS_CONTRACT_FILE_JOIN)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_DEMO_BS_CONTRACT_FILE_JOIN INCREMENT BY 1 START WITH 10000;

/*19*/
CREATE TABLE TB_DEMO_BS_CONSULTING
(
    IDX_DEMO_BS_CONSULTING	NUMBER(32) NOT NULL,
    CONSULTING_NUM NUMBER(20),
    IDX_DEMO_BS_APPLICAION	NUMBER(32) DEFAULT 0,
    IDX_DEMO_BUSINESS	NUMBER(32) DEFAULT 0,
    IDX_USER	NUMBER(32) DEFAULT 0,
    CONSULTING_TYPE	NUMBER(4),
    CONSULT_TYPE_ETC_STR	VARCHAR2(100),
    CONSULTING_STATUS	NUMBER(4),
    CONSULTING_GOAL	VARCHAR2(1000),
    REQ_DATE	DATE,
    RESULVATION_DATE	DATE,
    CONSULTING_DATE	DATE,
    CONSULTANT_IDX	NUMBER(32) DEFAULT 0,
    IS_CONSULTING_FILE	NUMBER(4),
    IS_RESULT_FILE	NUMBER(4),
    IS_CONSULTANT	NUMBER(4),
    CONSULT_ANSWER_TYPE NUMBER(4),
    IS_SHARE	NUMBER(4),
    MEMO	VARCHAR2(1000),
    IDX_ADMIN	NUMBER(32) DEFAULT 0,
    REG_DATE	DATE,
    CONSTRAINT DEMO_BS_CONSULTING_PK PRIMARY KEY (IDX_DEMO_BS_CONSULTING)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_DEMO_BS_CONSULTING INCREMENT BY 1 START WITH 10000;

/*20*/
CREATE TABLE TB_DEMO_BS_CONSULTING_FILE_JOIN
(
    IDX_DEMO_BS_CONSULTING_FILE_JOIN	NUMBER(32) NOT NULL,
    IDX_DEMO_BS_APPLICAION	NUMBER(32) DEFAULT 0,
    IDX_DEMO_BUSINESS	NUMBER(32) DEFAULT 0,
    IDX_DEMO_BS_CONSULTING	NUMBER(32) DEFAULT 0,
    FILE_TYPE	NUMBER(4),
    FILE_VERION	NUMBER(4),
    IS_LAST	NUMBER(4),
    IDX_FILE_INFO	NUMBER(32) DEFAULT 0,
    IDX_ADMIN	NUMBER(32) DEFAULT 0,
    REG_DATE	DATE,
    CONSTRAINT DEMO_BS_CONSULTING_FILE_JOIN_PK PRIMARY KEY (IDX_DEMO_BS_CONSULTING_FILE_JOIN)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_DEMO_BS_CONSULTING_FILE_JOIN INCREMENT BY 1 START WITH 10000;

/*21*/
CREATE TABLE TB_DEMO_BS_CONSULTANT_JOIN
(
    IDX_DEMO_BS_CONSULTANT_JOIN	NUMBER(32) NOT NULL,
    IDX_DEMO_BS_APPLICAION	NUMBER(32) DEFAULT 0,
    IDX_DEMO_BUSINESS	NUMBER(32) DEFAULT 0,
    IDX_ADMIN	NUMBER(32) DEFAULT 0,
    REG_DATE	DATE,
    CONSTRAINT DEMO_BS_CONSULTANT_JOIN_PK PRIMARY KEY (IDX_DEMO_BS_CONSULTANT_JOIN)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_DEMO_BS_CONSULTANT_JOIN INCREMENT BY 1 START WITH 10000;

/*22*/
CREATE TABLE TB_DEMO_BS_QNA
(
    IDX_DEMO_BS_QNA	NUMBER(32) NOT NULL,
    BS_QNA_NUM NUMBER(20),
    DEMO_BS_QNA_PARENT_IDX	NUMBER(32) DEFAULT 0,
    IDX_CORP_INFO	NUMBER(32) DEFAULT 0,
    IDX_USER	NUMBER(32) DEFAULT 0,
    QNA_TYPE	NUMBER(4),
    QNA_STATUS	NUMBER(4),
    QNA_SUBJECT	VARCHAR2(100),
    QNA_CONTENTS	VARCHAR2(3000),
    ANSWER_CONTENTS	VARCHAR2(3000),
    ANSWER_DATE	DATE,
    IS_Q_FILE	NUMBER(4),
    IS_ANSWER	NUMBER(4),
    IS_CONTINUE	NUMBER(4),
    IS_PARENT	NUMBER(4),
    QNA_ORDER	NUMBER(4),
    IS_PRIVACY_ACCEPT	NUMBER(4) DEFAULT 1,
    MEMO	VARCHAR2(1000),
    IDX_ADMIN	NUMBER(32) DEFAULT 0,
    REG_DATE	DATE,
    CONSTRAINT DEMO_BS_QNA_PK PRIMARY KEY (IDX_DEMO_BS_QNA)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_DEMO_BS_QNA INCREMENT BY 1 START WITH 10000;

/*23*/
CREATE TABLE TB_DEMO_BS_QES_FILE_JOIN
(
    IDX_DEMO_BS_QES_FILE_JOIN	NUMBER(32) NOT NULL,
    IDX_DEMO_BS_QNA	NUMBER(32) DEFAULT 0,
    IDX_FILE_INFO	NUMBER(32) DEFAULT 0,
    IDX_USER	NUMBER(32) DEFAULT 0,
    REG_DATE	DATE,
    CONSTRAINT DEMO_BS_QES_FILE_JOIN_PK PRIMARY KEY (IDX_DEMO_BS_QES_FILE_JOIN)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_DEMO_BS_QES_FILE_JOIN INCREMENT BY 1 START WITH 10000;

/*24*/
CREATE TABLE TB_DEMO_BS_REPORT
(
    IDX_DEMO_BS_REPORT	NUMBER(32) NOT NULL,
    IDX_USER_DEMO_BS	NUMBER(32) DEFAULT 0,
    IDX_CORP_INFO	NUMBER(32) DEFAULT 0,
    IDX_USER	NUMBER(32) DEFAULT 0,
    DEMO_BS_REPORT_CODE	VARCHAR2(40),
    DEMO_BS_REPORT_STATUS	NUMBER(4),
    IS_REPORT_REQ_FILE	NUMBER(4),
    IS_REPORT_FILE	NUMBER(4),
    MEMO	VARCHAR2(1000),
    IDX_ADMIN	NUMBER(32) DEFAULT 0,
    REG_DATE	DATE,
    CONSTRAINT DEMO_BS_REPORT_PK PRIMARY KEY (IDX_DEMO_BS_REPORT)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_DEMO_BS_REPORT INCREMENT BY 1 START WITH 10000;

/*25*/
CREATE TABLE TB_DEMO_BS_REPORT_FILE_JOIN
(
    IDX_DEMO_BS_REPORT_FILE_JOIN	NUMBER(32) NOT NULL,
    IDX_DEMO_BS_REPORT	NUMBER(32) DEFAULT 0,
    FILE_TYPE	NUMBER(4),
    FILE_VERION	NUMBER(4),
    IS_LAST	NUMBER(4),
    IDX_FILE_INFO	NUMBER(32) DEFAULT 0,
    IDX_USER	NUMBER(32) DEFAULT 0,
    IDX_ADMIN	NUMBER(32) DEFAULT 0,
    REG_DATE	DATE,
    CONSTRAINT DEMO_BS_REPORT_FILE_JOIN_PK PRIMARY KEY (IDX_DEMO_BS_REPORT_FILE_JOIN)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_DEMO_BS_REPORT_FILE_JOIN INCREMENT BY 1 START WITH 10000;



/*26 - new*/
DROP TABLE TB_USER_DEMO_BS;

CREATE TABLE TB_USER_DEMO_BS
(
    IDX_USER_DEMO_BS	NUMBER(32)  DEFAULT 0,
    IDX_DEMO_BUSINESS	NUMBER(32)  DEFAULT 0,
    USER_DEMOBS_STATUS NUMBER(4)  DEFAULT 0,
    IDX_USER	NUMBER(32),
    USER_DEMO_BS_APP_CODE	VARCHAR2(20),
    APP_STEP	NUMBER(4),
    USER_DEMO_BS_TYPE	NUMBER(4),
    IDX_CORP_INFO	NUMBER(32),
    CORP_NAME	VARCHAR2(100),
    CORP_BIRTH	VARCHAR2(20),
    CORP_NUM	VARCHAR2(20),
    CORP_REG_NUM	VARCHAR2(20),
    CORP_ADDR	VARCHAR2(1000),
    CORP_ADDR2	VARCHAR2(1000),
    CORP_RND_ADDR	VARCHAR2(1000),
    CORP_RND_ADDR2	VARCHAR2(1000),
    CORP_PHONE	VARCHAR2(40),
    LAB_PHONE	VARCHAR2(40),
    CAPITAL_AMOUNT	NUMBER(20) DEFAULT 0,
    CORP_SALES_AMOUNT	NUMBER(10),
    CORP_ER	NUMBER(10),
    EMPLOYEES_COUNT	NUMBER(10),
    BS_TYPE1	VARCHAR2(20),
    BS_TYPE2	VARCHAR2(20),
    MAIN_PRODUCT	VARCHAR2(200),
    REQ_FACILITY	NUMBER(4),
    DEMOBS_TECH_PLAN	VARCHAR2(100),
    CEO_NAME	VARCHAR2(100),
    CEO_MNUMBER	VARCHAR2(20),
    CEO_PNUMBER	VARCHAR2(20),
    CEO_EMAIL	VARCHAR2(400),
    CEO_ADDRESS	VARCHAR2(1000),
    CEO_ADDRESS2 VARCHAR2(1000),
    MAN_NAME	VARCHAR2(100),
    MAN_DPART VARCHAR2(100),
    MAN_ROLE VARCHAR2(200),
    MAN_MNUMBER	VARCHAR2(20),
    MAN_PNUMBER	VARCHAR2(20),
    MAN_EMAIL	VARCHAR2(400),
    USER_DEMO_TYPE	NUMBER(4),
    USER_DEMO_FACILITY	NUMBER(4),
    USER_DEMO_WAY	NUMBER(4),
    USER_DEMO_REPEAT	NUMBER(4),
    USER_DEMO_GOAL	NUMBER(4),
    USER_DEMO_OPTION	NUMBER(4),
    USER_DEMO_IS_CROPS NUMBER(4),
    USER_DEMO_CROPS	VARCHAR2(100),
    CULTURE_SOIL	NUMBER(4),
    DEMO_TYPE	NUMBER(4),

    DEMO_START_DATE	DATE,
    DEMO_END_DATE	DATE,

    FARMING_START_DATE DATE,
        FARMING_END_DATE DATE,
        FARMING_REPEAT NUMBER(4),

    RESIDENT_TYPE	NUMBER(4),
    RESIDENT_ETC	VARCHAR2(100),
    STAFF_NUM	NUMBER(10),
    IS_CHANGE	NUMBER(4),
    IS_CONFIRM	NUMBER(4),
    IS_SHARE	NUMBER(4),
    COSTAT_CODE	VARCHAR2(20),
    IS_OFFICE_OWER	NUMBER(4) DEFAULT 0,
    IS_LAB_OWER	NUMBER(4) DEFAULT 0,
    MAN_TOTAL	NUMBER(4) DEFAULT 0,
    MAN_OFFICER_COUNT	NUMBER(4) DEFAULT 0,
    MAN_LAB_COUNT	NUMBER(4) DEFAULT 0,
    MAN_ETC_COUNT	NUMBER(4) DEFAULT 0,

    LAB_EST_DATE	VARCHAR2(20),
    RND_RATE	NUMBER(4) DEFAULT 0,
    CONSOLIDATED_COMPANY VARCHAR2(100),

    CONSOLIDATED_COMPANY	VARCHAR2(100),
    HISTORY1	VARCHAR2(100),
    HISTORY1_DATE	VARCHAR2(20),
    HISTORY2	VARCHAR2(100),
    HISTORY2_DATE	VARCHAR2(20),
    HISTORY3	VARCHAR2(100),
    HISTORY3_DATE	VARCHAR2(20),
    PRIZE1	VARCHAR2(100),
    PRIZE1_DATE	VARCHAR2(20),
    PRIZE1_ORG	VARCHAR2(100),
    PRIZE1_ETC	VARCHAR2(100),
    PRIZE2	VARCHAR2(100),
    PRIZE2_DATE	VARCHAR2(20),
    PRIZE2_ORG	VARCHAR2(100),
    PRIZE2_ETC	VARCHAR2(100),
    PRIZE3	VARCHAR2(100),
    PRIZE3_DATE	VARCHAR2(20),
    PRIZE3_ORG	VARCHAR2(100),
    PRIZE3_ETC	VARCHAR2(100),

    REG_DATE	DATE,
    LAST_UPD_DATE	DATE,
    CONSTRAINT USER_DEMO_BS_PK PRIMARY KEY (IDX_USER_DEMO_BS)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;

CREATE SEQUENCE SEQ_USER_DEMO_BS INCREMENT BY 1 START WITH 10000;

/*27*/
CREATE TABLE TB_ASSET
(
    IDX_ASSET	NUMBER(32) NOT NULL,
    ASSET_CODE	VARCHAR2(40),
    ASSET_MAIN_CATEGORY_CODE	NUMBER(4),
    ASSET_SUB_CATEGORY_CODE	NUMBER(4),
    ASSET_DETAIL_CATEGORY_CODE	NUMBER(4),
    ASSET_NAME	VARCHAR2(100),
    ASSET_STATUS	NUMBER(4),
    IS_ASSET_PHOTO_FILE	NUMBER(4),
    ASSET_MANUFACTURE	VARCHAR2(100),
    ASSET_BRAND	VARCHAR2(100),
    ASSET_MODEL_NAME	VARCHAR2(100),
    ASSET_PID	VARCHAR2(100),
    ASSET_MANAGER_NAME	VARCHAR2(40),
    ASSET_LOC	VARCHAR2(100),
    ASSET_SPEC	VARCHAR2(100),
    REPRESENTATIVE_USE	VARCHAR2(100),
    MEMO	VARCHAR2(100),
    IDX_ADMIN	NUMBER(32) DEFAULT 0,
    REG_DATE	DATE,
    LAST_UPD_DATE	DATE,
    CONSTRAINT ASSET_PK PRIMARY KEY (IDX_ASSET)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_ASSET INCREMENT BY 1 START WITH 10000;

/*28*/
CREATE TABLE TB_ASSET_PHOTO_FILE_JOIN
(
    IDX_ASSET_PHOTO_FILE_JOIN	NUMBER(32) NOT NULL,
    IDX_ASSET	NUMBER(32) DEFAULT 0,
    FILE_TYPE	NUMBER(4),
    FILE_VERION	NUMBER(4),
    IS_LAST	NUMBER(4),
    IDX_FILE_INFO	NUMBER(32) DEFAULT 0,
    IDX_ADMIN	NUMBER(32) DEFAULT 0,
    REG_DATE	DATE,
    CONSTRAINT ASSET_PHOTO_FILE_JOIN_PK PRIMARY KEY (IDX_ASSET_PHOTO_FILE_JOIN)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_ASSET_PHOTO_FILE_JOIN INCREMENT BY 1 START WITH 10000;

/*29*/
CREATE TABLE TB_SERVICE_CODE_GROUP
(
    IDX_SERVICE_CODE_GROUP	NUMBER(32) NOT NULL,
    CODE_GROUP	NUMBER(4),
    CODE_GROUP_EXPLANATION	VARCHAR2(100),
    REG_DATE	DATE,
    CONSTRAINT SERVICE_CODE_GROUP_PK PRIMARY KEY (IDX_SERVICE_CODE_GROUP)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_SERVICE_CODE_GROUP INCREMENT BY 1 START WITH 10000;

/*30*/
CREATE TABLE TB_SERVICE_CODE
(
    IDX_SERVICE_CODE	NUMBER(32) NOT NULL,
    CODE	NUMBER(4),
    CODE_STRING_KOR	VARCHAR2(20),
    CODE_STRING_ENG	VARCHAR2(20),
    CODE_STRING_CHN	VARCHAR2(20),
    CODE_STRING_JPN	VARCHAR2(20),
    CODE_EXPLANATION	VARCHAR2(100),
    REG_DATE	DATE,
    CONSTRAINT SERVICE_CODE_PK PRIMARY KEY (IDX_SERVICE_CODE)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_SERVICE_CODE INCREMENT BY 1 START WITH 10000;

/*31*/
CREATE TABLE TB_ASSET_MANAGE
(
    IDX_ASSET_MANAGE	NUMBER(32) NOT NULL,
    ASSET_MANAGE_CODE	VARCHAR2(40),
    IDX_ASSET_RESERVATION	NUMBER(32) DEFAULT 0,
    IDX_CORP_INFO	NUMBER(32) DEFAULT 0,
    IDX_USER	NUMBER(32) DEFAULT 0,
    MANAGE_STATUS	NUMBER(4),
    AMOUNT	NUMBER(10),
    MEMO	VARCHAR2(1000),
    IDX_ADMIN	NUMBER(32) DEFAULT 0,
    IDX_UPDATE_ADMIN	NUMBER(32) DEFAULT 0,
    REG_DATE	DATE,
    LAST_UPD_DATE	DATE,
    CONSTRAINT ASSET_MANAGE_PK PRIMARY KEY (IDX_ASSET_MANAGE)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_ASSET_MANAGE INCREMENT BY 1 START WITH 10000;

/*32*/
CREATE TABLE TB_ASSET_RESERVATION
(
    IDX_ASSET_RESERVATION	NUMBER(32) NOT NULL,
    ASSET_RESERVAION_CODE	VARCHAR2(40),
    IDX_USER_DEMO_BS	NUMBER(32) DEFAULT 0,
    IDX_CORP_INFO	NUMBER(32) DEFAULT 0,
    IDX_USER	NUMBER(32) DEFAULT 0,
    IDX_ADMIN	NUMBER(32) DEFAULT 0,
    RESERVAION_STATUS	NUMBER(4),
    ASSET_USAGE	VARCHAR2(1000),
    IS_END	NUMBER(4),
    IS_RETURN	NUMBER(4),
    USE_START_DATE	DATE,
    USE_END_DATE	DATE,
    PERMISSION_DATE	DATE,
    REG_DATE	DATE,
    LAST_UPD_DATE	DATE,
    CONSTRAINT ASSET_RESERVATION_PK PRIMARY KEY (IDX_ASSET_RESERVATION)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_ASSET_RESERVATION INCREMENT BY 1 START WITH 10000;

/*33*/
CREATE TABLE TB_ASSET_RESERVATION_ITEM
(
    IDX_ASSET_RESERVATION_ITEM	NUMBER(32) NOT NULL,
    ASSET_CODE	VARCHAR2(40),
    IDX_ASSET_RESERVATION	NUMBER(32) DEFAULT 0,
    ASSET_MANAGE_CODE	VARCHAR2(40),
    IDX_ASSET_MANAGE	NUMBER(32) DEFAULT 0,
    AMOUNT	NUMBER(10),
    RESERVATION_ITEM_STATUS	NUMBER(4),
    NOT_ALLOWED_CODE	NUMBER(4),
    REG_DATE	DATE,
    LAST_UPD_DATE	DATE,
    CONSTRAINT ASSET_RESERVATION_ITEM_PK PRIMARY KEY (IDX_ASSET_RESERVATION_ITEM)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_ASSET_RESERVATION_ITEM INCREMENT BY 1 START WITH 10000;

/*34*/
CREATE TABLE TB_SCHEDULE_ITEM
(
    IDX_SCHEDULE_ITEM	NUMBER(32) NOT NULL,
    IDX_SCHEDULE	NUMBER(32) DEFAULT 0,
    START_DATE	DATE,
    END_DATE	DATE,
    SCHEDULE_TYPE	NUMBER(4),
    NOTI_TYPE	NUMBER(4),
    NOTI_DATE	DATE,
    SHOW_TYPE	NUMBER(4),
    GRADE	NUMBER(4),
    COLOR_CODE	VARCHAR2(10),
    CONTENTS	VARCHAR2(1000),
    IDX_ADMIN	NUMBER(32) DEFAULT 0,
    REG_DATE	DATE,
    LAST_UPD_DATE	DATE,
    CONSTRAINT SCHEDULE_ITEM_PK PRIMARY KEY (IDX_SCHEDULE_ITEM)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_SCHEDULE_ITEM INCREMENT BY 1 START WITH 10000;

/*35*/
CREATE TABLE TB_USER(
    IDX_USER	NUMBER(32) NOT NULL,
    USER_ID	VARCHAR2(255),
    USER_PW	VARCHAR2(255),
    USER_NAME	VARCHAR2(40),
    ADDR	VARCHAR2(255),
    TEL_NUM	VARCHAR2(20),
    MPHONE_NUM	VARCHAR2(20),
    EMAIL	VARCHAR2(356),
    USER_TYPE	NUMBER(4) DEFAULT 0,
    BAN_MEMO	VARCHAR2(1000),
    IS_SERVICE_AGREE	NUMBER(4) DEFAULT 1,
    SERVICE_AGREE_VER	NUMBER(4) DEFAULT 1,
    IS_PRIVACY_AGREE	NUMBER(4) DEFAULT 1,
    PRIVACY_AGREE_VER	NUMBER(4) DEFAULT 1,
    IS_THIRD_PARTY_AGREE	NUMBER(4) DEFAULT 1,
    THIRD_PARTY_AGREE_VER	NUMBER(4) DEFAULT 1,
    IS_MAKETING_AGREE	NUMBER(4) DEFAULT 1,
    MAKETING_AGREE_VER	NUMBER(4) DEFAULT 1,
    AUTH_STATUS	NUMBER(4) DEFAULT 0,
    IS_APPLICANT	NUMBER(4) DEFAULT 0,
    IS_CORPORATE_MEMBER	NUMBER(4) DEFAULT 0,
    IDX_CORP_INFO	NUMBER(32) DEFAULT 0,
    SIGN_IN_TYPE	NUMBER(4) DEFAULT 0,
    IS_SMS_AGREE	NUMBER(4) DEFAULT 0,
    IS_EMAIL_AGREE	NUMBER(4) DEFAULT 0,
    REG_DATE	DATE,
    LAST_UPD_DATE	DATE,
    CONSTRAINT USER_PK PRIMARY KEY (IDX_USER)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;

CREATE SEQUENCE SEQ_USER INCREMENT BY 1 START WITH 10000;

/*36*/
CREATE TABLE TB_USER_PW_HISTORY
(
    IDX_USER_PW_HISTORY	NUMBER(32) NOT NULL,
    IDX_USER	NUMBER(32) DEFAULT 0,
    PAST_USER_PW	VARCHAR2(255),
    REG_DATE	DATE,
    CONSTRAINT USER_PW_HISTORY_PK PRIMARY KEY (IDX_USER_PW_HISTORY)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_USER_PW_HISTORY INCREMENT BY 1 START WITH 10000;

/*37*/
CREATE TABLE TB_ADMIN
(
    IDX_ADMIN	NUMBER(32) NOT NULL,
    ADMIN_ID	VARCHAR2(255),
    ADMIN_PW	VARCHAR2(255),
    ADMIN_NAME	VARCHAR2(40),
    CORPORATE	NUMBER(4),
    CORPORATE_NAME	VARCHAR2(40),
    DEPARTMENT	VARCHAR2(40),
    JOB_TITLE	VARCHAR2(40),
    AUTH_STATUS	NUMBER(4),
    TEL_NUM	VARCHAR2(20),
    MPHONE_NUM	VARCHAR2(20),
    EMAIL	VARCHAR2(255),
    ADMIN_TYPE	NUMBER(4),
    AUTH_ADMIN_IDX	NUMBER(32) DEFAULT 0,
    SIGN_IN_TYPE	NUMBER(4),
    REG_DATE	DATE,
    LAST_UPD_DATE	DATE,
    CONSTRAINT ADMIN_PK PRIMARY KEY (IDX_ADMIN)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_ADMIN INCREMENT BY 1 START WITH 10000;

/*92*/
CREATE TABLE TB_SERVICE_AGREE
(
    IDX_SERVICE_AGREE	NUMBER(32),
    VERSION	NUMBER(4),
    CONTENTS	CLOB,
    IDX_ADMIN	NUMBER(32),
    REG_DATE	DATE,
    LAST_UPD_DATE	DATE,
    CONSTRAINT SERVICE_AGREE_PK PRIMARY KEY (IDX_SERVICE_AGREE)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_SERVICE_AGREE INCREMENT BY 1 START WITH 10000;

/*93*/
CREATE TABLE TB_PRIVACY_AGREE
(
    IDX_PRIVACY_AGREE	NUMBER(32),
    VERSION	NUMBER(4),
    CONTENTS	CLOB,
    IDX_ADMIN	NUMBER(32),
    REG_DATE	DATE,
    LAST_UPD_DATE	DATE,
    CONSTRAINT PRIVACY_AGREE_PK PRIMARY KEY (IDX_PRIVACY_AGREE)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_PRIVACY_AGREE INCREMENT BY 1 START WITH 10000;

/*94*/
CREATE TABLE TB_THIRD_PARTY_AGREE
(
    IDX_THIRD_PARTY_AGREE	NUMBER(32),
    VERSION	NUMBER(4),
    CONTENTS	CLOB,
    IDX_ADMIN	NUMBER(32),
    REG_DATE	DATE,
    LAST_UPD_DATE	DATE,
    CONSTRAINT THIRD_PARTY_AGREE_PK PRIMARY KEY (IDX_THIRD_PARTY_AGREE)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_THIRD_PARTY_AGREE INCREMENT BY 1 START WITH 10000;

/*95*/
CREATE TABLE TB_MAKETING_AGREE
(
    IDX_MAKETING_AGREE	NUMBER(32),
    VERSION	NUMBER(4),
    CONTENTS	CLOB,
    IDX_ADMIN	NUMBER(32),
    REG_DATE	DATE,
    LAST_UPD_DATE	DATE,
    CONSTRAINT MAKETING_AGREE_PK PRIMARY KEY (IDX_MAKETING_AGREE)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_MAKETING_AGREE INCREMENT BY 1 START WITH 10000;

















/*96*/
CREATE TABLE  TB_CO_WORKER
(
    IDX_CO_WORKER	NUMBER(32),
    COWORKER_NAME VARCHAR2(40),
    DEVISION	VARCHAR2(60),
    DEPARTMENT	VARCHAR2(60),
    DEPARTMENT_SUB	VARCHAR2(60),
    JOB_TITLE	VARCHAR2(60),
    JOB_ROLE	VARCHAR2(60),
    TEL_NUM	VARCHAR2(60),
    MPHONE_NUM	VARCHAR2(20),
    EMAIL	VARCHAR2(255),
    IS_SHOW	NUMBER(4) DEFAULT 1,
    REG_DATE	DATE,
    CONSTRAINT CO_WORKER_PK PRIMARY KEY (IDX_CO_WORKER)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_CO_WORKER INCREMENT BY 1 START WITH 10000;







/*97*/
CREATE TABLE TB_NOTICE
(
    IDX_NOTICE	NUMBER(32),
    NOTICE_CODE	VARCHAR2(100),
    NOTICE_NUM	NUMBER(20),
    SUBJECT	VARCHAR2(100),
    NOTICE_CONTENTS	CLOB,
    IS_FILE	NUMBER(4) DEFAULT 0,
    IS_NEW	NUMBER(4) DEFAULT 0,
    IS_MAIN_PAGE	NUMBER(4) DEFAULT 0,
    IS_IMPORTANT	NUMBER(4) DEFAULT 0,
    IS_SHOW	NUMBER(4) DEFAULT 0,
    VIEW_COUNT	NUMBER(20),
    NOTICE_STATUS	NUMBER(4) DEFAULT 0,
    POSTING_START_DATE	DATE,
    POSTING_END_DATE	DATE,
    DOC_VERSION	NUMBER(4),
    MEMO	VARCHAR2(1000),
    SEARCH_TAG	NUMBER(32),
    AUTHOR	VARCHAR2(40),
    IDX_ADMIN	NUMBER(32),
    CONFIRM_ADMIN_IDX	NUMBER(32),
    REG_DATE	DATE,
    LAST_UPD_DATE	DATE,
    CONSTRAINT NOTICE_PK PRIMARY KEY (IDX_NOTICE)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_NOTICE INCREMENT BY 1 START WITH 10000;

/*98*/
CREATE TABLE TB_NOTICE_FILE_JOIN
(
    IDX_NOTICE_FILE_JOIN	NUMBER(32),
    IDX_NOTICE	NUMBER(32),
    FILE_TYPE	NUMBER(4) DEFAULT 0,
    IDX_FILE_INFO	NUMBER(32),
    IDX_ADMIN	NUMBER(32),
    REG_DATE	DATE,
    CONSTRAINT NOTICE_FILE_JOIN_PK PRIMARY KEY (IDX_NOTICE_FILE_JOIN)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_NOTICE_FILE_JOIN INCREMENT BY 1 START WITH 10000;

/*99*/
CREATE TABLE TB_BS_ANNOUNCEMENT_FILE_JOIN
(
    IDX_BS_ANNOUNCEMENT_FILE_JOIN	NUMBER(32),
    IDX_BS_ANNOUNCEMENT	NUMBER(32),
    FILE_TYPE	NUMBER(4) DEFAULT 0,
    IDX_FILE_INFO	NUMBER(32),
    IDX_ADMIN	NUMBER(32),
    REG_DATE	DATE,
    CONSTRAINT BS_ANNOUNCEMENT_FILE_JOIN_PK PRIMARY KEY (IDX_BS_ANNOUNCEMENT_FILE_JOIN)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_BS_ANNOUNCEMENT_FILE_JOIN INCREMENT BY 1 START WITH 10000;


CREATE TABLE TB_EVENT_CONTENT
(
    IDX_EVENT_CONTENT	NUMBER(32),
    EVENT_CONTENT_CODE	VARCHAR2(100),
    EVENT_CONTENT_NUM	NUMBER(20),
    SUBJECT	VARCHAR2(100),
    CONTENTS	CLOB,
    IS_FILE	NUMBER(4) DEFAULT 0,
    IS_NEW	NUMBER(4) DEFAULT 0,
    IS_MAIN_PAGE	NUMBER(4) DEFAULT 0,
    IS_IMPORTANT	NUMBER(4) DEFAULT 0,
    IS_SHOW	NUMBER(4) DEFAULT 0,
    VIEW_COUNT	NUMBER(20),
    EVENT_CONTENT_STATUS	NUMBER(4) DEFAULT 0,
    EVENT_START_DATE	DATE,
    EVENT_END_DATE	DATE,
    DOC_VERSION	NUMBER(4) DEFAULT 1,
    MEMO	VARCHAR2(1000),
    SEARCH_TAG	NUMBER(32),
    AUTHOR	VARCHAR2(40),
    THUMB_IMG_FILE_IDX	NUMBER(32),
    IDX_ADMIN	NUMBER(32),
    CONFIRM_ADMIN_IDX	NUMBER(32),
    REG_DATE	DATE,
    LAST_UPD_DATE	DATE,
    CONSTRAINT EVENT_CONTENT_PK PRIMARY KEY (IDX_EVENT_CONTENT)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_EVENT_CONTENT INCREMENT BY 1 START WITH 10000;


CREATE TABLE TB_EVENT_CONTENT_FILE_JOIN
(
    IDX_EVENT_CONTENT_FILE_JOIN	NUMBER(32),
    IDX_EVENT_CONTENT	NUMBER(32),
    FILE_TYPE	NUMBER(4) DEFAULT 0,
    IDX_FILE_INFO	NUMBER(32),
    IDX_ADMIN	NUMBER(32),
    REG_DATE	DATE,
    CONSTRAINT EVENT_CONTENT_FILE_JOIN_PK PRIMARY KEY (IDX_EVENT_CONTENT_FILE_JOIN)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_EVENT_CONTENT_FILE_JOIN INCREMENT BY 1 START WITH 10000;





CREATE TABLE TB_PR_CONTENT
(
    IDX_PR_CONTENT	NUMBER(32),
    PR_CONTENT_CODE	VARCHAR2(100),
    PR_CONTENT_NUM	NUMBER(20),
    SUBJECT	VARCHAR2(100),
    PR_CONTENTS	CLOB,
    IS_FILE	NUMBER(4) DEFAULT 0,
    IS_NEW	NUMBER(4) DEFAULT 0,
    IS_MAIN_PAGE	NUMBER(4) DEFAULT 0,
    IS_IMPORTANT	NUMBER(4) DEFAULT 0,
    IS_SHOW	NUMBER(4) DEFAULT 0,
    VIEW_COUNT	NUMBER(20),
    PR_CONTENT_STATUS	NUMBER(4) DEFAULT 0,
    SHOW_START_DATE	DATE,
    SHOW_END_DATE	DATE,
    DOC_VERSION	NUMBER(4) DEFAULT 1,
    MEMO	VARCHAR2(1000),
    SEARCH_TAG	NUMBER(32),
    AUTHOR	VARCHAR2(40),
    THUMB_IMG_FILE_IDX	NUMBER(32),
    IDX_ADMIN	NUMBER(32),
    CONFIRM_ADMIN_IDX	NUMBER(32),
    REG_DATE	DATE,
    LAST_UPD_DATE	DATE,
    CONSTRAINT PR_CONTENT_PK PRIMARY KEY (IDX_PR_CONTENT)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_PR_CONTENT INCREMENT BY 1 START WITH 10000;



CREATE TABLE TB_PR_CONTENT_FILE_JOIN
(
    IDX_PR_CONTENT_FILE_JOIN	NUMBER(32),
    IDX_PR_CONTENT	NUMBER(32),
    FILE_TYPE	NUMBER(4) DEFAULT 0,
    IDX_FILE_INFO	NUMBER(32),
    IDX_ADMIN	NUMBER(32),
    REG_DATE	DATE,
    CONSTRAINT PR_CONTENT_FILE_JOIN_PK PRIMARY KEY (IDX_PR_CONTENT_FILE_JOIN)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_PR_CONTENT_FILE_JOIN INCREMENT BY 1 START WITH 10000;



/*44*/
CREATE TABLE TB_VISIT_REQ
(
    IDX_VISIT_REQ	NUMBER(32),
    VISIT_REQ_NUM	NUMBER(20),
    GROUP_NAME	VARCHAR2(40),
    VISITOR	VARCHAR2(40),
    RESULVATION_DATE	DATE,
    VISITOR_COUNT	NUMBER(10),
    VISITOR_MPHONE_NUM	VARCHAR2(20),
    VISITOR_EMAIL	VARCHAR2(250),
    VISITOR_ADRESS	VARCHAR2(250),
    VISIT_GOAL	VARCHAR2(400),
    QUESTION	VARCHAR2(400),
    VISIT_REQ_STATUS	NUMBER(4) DEFAULT 0,
    IS_PRIVACY_ACCEPT	NUMBER(4) DEFAULT 1,
    IS_GROUP	NUMBER(4) DEFAULT 0,
    IS_CANCEL	NUMBER(4) DEFAULT 0,
    IS_MANAGER NUMBER(4) DEFAULT 0,
    IDX_MANAGER	NUMBER(32),
    IS_DURATION	NUMBER(4) DEFAULT 0,
    DURATION_AMOUNT	NUMBER(10),
    MEMO	VARCHAR2(1000),
    IDX_VISIT_DATA	NUMBER(32),
    IDX_USER	NUMBER(32),
    IDX_ADMIN	NUMBER(32),
    REG_DATE	DATE,
    CONSTRAINT VISIT_REQ_PK PRIMARY KEY (IDX_VISIT_REQ)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_VISIT_REQ INCREMENT BY 1 START WITH 10000;

/*45*/
CREATE TABLE TB_VISIT_DATA
(

    IDX_VISIT_DATA	NUMBER(32),
    CUR_DATE	DATE,
    POSSIBLE_COUNT	NUMBER(10) DEFAULT  0,
    RESULVATION_COUNT	NUMBER(10) DEFAULT  0,
    IS_ADMIN_CANCEL	NUMBER(4) DEFAULT  0,
    IMPOSSIBLE_REASON	VARCHAR2(400),
    VISIT_DATA_TYPE	NUMBER(4) DEFAULT  0,
    MEMO	VARCHAR2(1000),
    GROUP_IDX	NUMBER(32) DEFAULT  0,
    IDX_ADMIN	NUMBER(32),
    REG_DATE	DATE,
    CONSTRAINT VISIT_DATA_PK PRIMARY KEY (IDX_VISIT_DATA)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_VISIT_DATA INCREMENT BY 1 START WITH 10000;







CREATE TABLE TB_ADMIN_HISTORY
(
    IDX_ADMIN_HISTORY	NUMBER(32),
    IDX_ADMIN	NUMBER(32) DEFAULT 0,
    ADMIN_ID	VARCHAR2(255),
    ADMIN_NAME	VARCHAR2(40),
    WORK_TYPE	NUMBER(4),
    WORK_DETAIL	NUMBER(4),
    REG_DATE	DATE,
    CONSTRAINT ADMIN_HISTORY_PK PRIMARY KEY (IDX_ADMIN_HISTORY)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_ADMIN_HISTORY INCREMENT BY 1 START WITH 10000;













/*46*/
CREATE TABLE TB_GH_TWIN_CHAMBER
(



    CONSTRAINT GH_TWIN_CHAMBER_PK PRIMARY KEY (IDX_GH_TWIN_CHAMBER)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_GH_TWIN_CHAMBER INCREMENT BY 1 START WITH 10000;

/*47*/
CREATE TABLE TB_PLANT_PHYSIOLOGY_TESTER
(



    CONSTRAINT PLANT_PHYSIOLOGY_TESTER_PK PRIMARY KEY (IDX_PLANT_PHYSIOLOGY_TESTER)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_PLANT_PHYSIOLOGY_TESTER INCREMENT BY 1 START WITH 10000;

/*48*/
CREATE TABLE TB_ENV_VERIFYDATA_AIRCON_EFFECT
(



    CONSTRAINT ENV_VERIFYDATA_AIRCON_EFFECT_PK PRIMARY KEY (IDX_ENV_VERIFYDATA_AIRCON_EFFECT)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_ENV_VERIFYDATA_AIRCON_EFFECT INCREMENT BY 1 START WITH 10000;

/*49*/
CREATE TABLE TB_ENV_TEMPCONTROLLER
(



    CONSTRAINT ENV_TEMPCONTROLLER_PK PRIMARY KEY (IDX_ENV_TEMPCONTROLLER)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_ENV_TEMPCONTROLLER INCREMENT BY 1 START WITH 10000;

/*50*/
CREATE TABLE TB_ENV_DATA_ACQ_COMPOSITE_SENSOR
(



    CONSTRAINT ENV_DATA_ACQ_COMPOSITE_SENSOR_PK PRIMARY KEY (IDX_ENV_DATA_ACQ_COMPOSITE_SENSOR)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_ENV_DATA_ACQ_COMPOSITE_SENSOR INCREMENT BY 1 START WITH 10000;

/*51*/
CREATE TABLE TB_SURGE_TESTER
(



    CONSTRAINT SURGE_TESTER_PK PRIMARY KEY (IDX_SURGE_TESTER)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_SURGE_TESTER INCREMENT BY 1 START WITH 10000;

/*52*/
CREATE TABLE TB_MATERIAL_SMALL_DATA
(



    CONSTRAINT MATERIAL_SMALL_DATA_PK PRIMARY KEY (IDX_MATERIAL_SMALL_DATA)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_MATERIAL_SMALL_DATAINCREMENT BY 1 START WITH 10000;

/*53*/
CREATE TABLE TB_GROWTH_TESTER
(



    CONSTRAINT GROWTH_TESTER_PK PRIMARY KEY (IDX_GROWTH_TESTER)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_GROWTH_TESTER INCREMENT BY 1 START WITH 10000;

/*54*/
CREATE TABLE TB_MATERIAL_BIG_DATA
(



    CONSTRAINT MATERIAL_BIG_DATA_PK PRIMARY KEY (IDX_MATERIAL_BIG_DATA)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_MATERIAL_BIG_DATA INCREMENT BY 1 START WITH 10000;

/*55*/
CREATE TABLE TB_SUGAR_METER
(



    CONSTRAINT SUGAR_METER_PK PRIMARY KEY (IDX_SUGAR_METER)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_SUGAR_METER INCREMENT BY 1 START WITH 10000;

/*56*/
CREATE TABLE TB_COLOIMETER
(



    CONSTRAINT COLOIMETER_PK PRIMARY KEY (IDX_COLOIMETER)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_COLOIMETER INCREMENT BY 1 START WITH 10000;

/*57*/
CREATE TABLE TB_MOISTURE_METER
(



    CONSTRAINT MOISTURE_METER_PK PRIMARY KEY (IDX_MOISTURE_METER)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_MOISTURE_METER INCREMENT BY 1 START WITH 10000;

/*58*/
CREATE TABLE TB_CHLOROPHYLL_METER
(



    CONSTRAINT CHLOROPHYLL_METER_PK PRIMARY KEY (IDX_CHLOROPHYLL_METER)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_CHLOROPHYLL_METER INCREMENT BY 1 START WITH 10000;

/*59*/
CREATE TABLE TB_WIND_TESTER
(



    CONSTRAINT WIND_TESTER_PK PRIMARY KEY (IDX_WIND_TESTER)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_WIND_TESTER INCREMENT BY 1 START WITH 10000;

/*60*/
CREATE TABLE TB_CO2_TESTER
(



    CONSTRAINT CO2_TESTER_PK PRIMARY KEY (IDX_CO2_TESTER)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_CO2_TESTER INCREMENT BY 1 START WITH 10000;

/*61*/
CREATE TABLE TB_PH_TESTER
(



    CONSTRAINT PH_TESTER_PK PRIMARY KEY (IDX_PH_TESTER)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_PH_TESTER INCREMENT BY 1 START WITH 10000;

/*62*/
CREATE TABLE TB_SOIL_MOISTURE_SENSOR_TESTER
(



    CONSTRAINT SOIL_MOISTURE_SENSOR_TESTER_PK PRIMARY KEY (IDX_SOIL_MOISTURE_SENSOR_TESTER)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_SOIL_MOISTURE_SENSOR_TESTER INCREMENT BY 1 START WITH 10000;

/*63*/
CREATE TABLE TB_SUNLIGHT_SENSOR_TESTER
(



    CONSTRAINT SUNLIGHT_SENSOR_TESTER_PK PRIMARY KEY (IDX_SUNLIGHT_SENSOR_TESTER)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_SUNLIGHT_SENSOR_TESTER INCREMENT BY 1 START WITH 10000;

/*64*/
CREATE TABLE TB_AC_MOTOR_TESTER
(



    CONSTRAINT AC_MOTOR_TESTER_PK PRIMARY KEY (IDX_AC_MOTOR_TESTER)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_AC_MOTOR_TESTER INCREMENT BY 1 START WITH 10000;

/*65*/
CREATE TABLE TB_DC_MOTOR_TESTER
(



    CONSTRAINT DC_MOTOR_TESTER_PK PRIMARY KEY (IDX_DC_MOTOR_TESTER)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_DC_MOTOR_TESTER INCREMENT BY 1 START WITH 10000;

/*66*/
CREATE TABLE TB_NUTRIENT_SUPPLY_TESTER
(



    CONSTRAINT NUTRIENT_SUPPLY_TESTER_PK PRIMARY KEY (IDX_NUTRIENT_SUPPLY_TESTER)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_NUTRIENT_SUPPLY_TESTER INCREMENT BY 1 START WITH 10000;

/*67*/
CREATE TABLE TB_WEIGHT_TESTER
(



    CONSTRAINT WEIGHT_TESTER_PK PRIMARY KEY (IDX_WEIGHT_TESTER)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_WEIGHT_TESTER INCREMENT BY 1 START WITH 10000;

/*68*/
CREATE TABLE TB_CROP_SAMPLER
(



    CONSTRAINT CROP_SAMPLER_PK PRIMARY KEY (IDX_CROP_SAMPLER)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_CROP_SAMPLER INCREMENT BY 1 START WITH 10000;

/*69*/
CREATE TABLE TB_CROP_PRECISION_ANALYSIS_TESTER
(



    CONSTRAINT CROP_PRECISION_ANALYSIS_TESTER_PK PRIMARY KEY (IDX_CROP_PRECISION_ANALYSIS_TESTER)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_CROP_PRECISION_ANALYSIS_TESTER INCREMENT BY 1 START WITH 10000;

/*70*/
CREATE TABLE TB_MULTI_WATER_ANALYSIS_TOC_TESTER
(



    CONSTRAINT MULTI_WATER_ANALYSIS_TOC_TESTER_PK PRIMARY KEY (IDX_MULTI_WATER_ANALYSIS_TOC_TESTER)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_MULTI_WATER_ANALYSIS_TOC_TESTER INCREMENT BY 1 START WITH 10000;

/*71*/
CREATE TABLE TB_MULTI_WATER_ANALYSIS_TESTER
(



    CONSTRAINT MULTI_WATER_ANALYSIS_TESTER_PK PRIMARY KEY (IDX_MULTI_WATER_ANALYSIS_TESTER)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_MULTI_WATER_ANALYSIS_TESTER INCREMENT BY 1 START WITH 10000;

/*72*/
CREATE TABLE TB_GH_AIR_PERMEABILITY_TESTER
(



    CONSTRAINT GH_AIR_PERMEABILITY_TESTER_PK PRIMARY KEY (IDX_GH_AIR_PERMEABILITY_TESTER)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_GH_AIR_PERMEABILITY_TESTER INCREMENT BY 1 START WITH 10000;

/*73*/
CREATE TABLE TB_GH_SHADING_RATE_TESTER
(



    CONSTRAINT GH_SHADING_RATE_TESTER_PK PRIMARY KEY (IDX_GH_SHADING_RATE_TESTER)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_GH_SHADING_RATE_TESTER INCREMENT BY 1 START WITH 10000;

/*74*/
CREATE TABLE TB_GH_LUMINANCE_TESTER
(



    CONSTRAINT GH_LUMINANCE_TESTER_PK PRIMARY KEY (IDX_GH_LUMINANCE_TESTER)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_GH_LUMINANCE_TESTER INCREMENT BY 1 START WITH 10000;

/*75*/
CREATE TABLE TB_DO_TESTER
(



    CONSTRAINT DO_TESTER_PK PRIMARY KEY (IDX_DO_TESTER)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_DO_TESTER INCREMENT BY 1 START WITH 10000;

/*76*/
CREATE TABLE TB_VERIFYDATA_HEATFLOW_DATA
(



    CONSTRAINT VERIFYDATA_HEATFLOW_DATA_PK PRIMARY KEY (IDX_VERIFYDATA_HEATFLOW_DATA)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_VERIFYDATA_HEATFLOW_DATA INCREMENT BY 1 START WITH 10000;

/*77*/
CREATE TABLE TB_VERIFYDATA_VIBRATION_DATA
(



    CONSTRAINT VERIFYDATA_VIBRATION_DATA_PK PRIMARY KEY (IDX_VERIFYDATA_VIBRATION_DATA)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_VERIFYDATA_VIBRATION_DATA INCREMENT BY 1 START WITH 10000;

/*78*/
CREATE TABLE TB_VERIFYDATA_HOTSHOCK_DATA
(



    CONSTRAINT VERIFYDATA_HOTSHOCK_DATA_PK PRIMARY KEY (IDX_VERIFYDATA_HOTSHOCK_DATA)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_VERIFYDATA_HOTSHOCK_DATA INCREMENT BY 1 START WITH 10000;

/*79*/
CREATE TABLE TB_VERIFYDATA_WATERPROOF_DATA
(



    CONSTRAINT VERIFYDATA_WATERPROOF_DATA_PK PRIMARY KEY (IDX_VERIFYDATA_WATERPROOF_DATA)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_VERIFYDATA_WATERPROOF_DATA INCREMENT BY 1 START WITH 10000;

/*80*/
CREATE TABLE TB_VERIFYDATA_SENSORTEST_DATA
(



    CONSTRAINT VERIFYDATA_SENSORTEST_DATA_PK PRIMARY KEY (IDX_VERIFYDATA_SENSORTEST_DATA)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_VERIFYDATA_SENSORTEST_DATA INCREMENT BY 1 START WITH 10000;

/*81*/
CREATE TABLE TB_VERIFYDATA_MOISTURE_DATA
(



    CONSTRAINT VERIFYDATA_MOISTURE_DATA_PK PRIMARY KEY (IDX_VERIFYDATA_MOISTURE_DATA)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_CORP_CEO INCREMENT BY 1 START WITH 10000;

/*82*/
CREATE TABLE TB_VERIFYDATA_ECSENSOR_DATA
(



    CONSTRAINT VERIFYDATA_ECSENSOR_DATA_PK PRIMARY KEY (IDX_VERIFYDATA_ECSENSOR_DATA)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_VERIFYDATA_ECSENSOR_DATA INCREMENT BY 1 START WITH 10000;

/*83*/
CREATE TABLE TB_VERIFYDATA_THERMOHYGROSTAT_DATA
(



    CONSTRAINT VERIFYDATA_THERMOHYGROSTAT_DATA_PK PRIMARY KEY (IDX_VERIFYDATA_THERMOHYGROSTAT_DATA)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_VERIFYDATA_THERMOHYGROSTAT_DATA INCREMENT BY 1 START WITH 10000;

/*84*/
CREATE TABLE TB_VERIFYDATA_HOTSHOCK_ROBOT_DATA
(



    CONSTRAINT VERIFYDATA_HOTSHOCK_ROBOT_DATA_PK PRIMARY KEY (IDX_VERIFYDATA_HOTSHOCK_ROBOT_DATA)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_VERIFYDATA_HOTSHOCK_ROBOT_DATA INCREMENT BY 1 START WITH 10000;

/*85*/
CREATE TABLE TB_VERIFYDATA_DUST_DATA
(



    CONSTRAINT VERIFYDATA_DUST_DATA_PK PRIMARY KEY (IDX_VERIFYDATA_DUST_DATA)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_VERIFYDATA_DUST_DATA INCREMENT BY 1 START WITH 10000;

/*86*/
CREATE TABLE TB_VERIFYDATA_WATERPROOF_ROBOT_DATA
(



    CONSTRAINT VERIFYDATA_WATERPROOF_ROBOT_DATA_PK PRIMARY KEY (IDX_VERIFYDATA_WATERPROOF_ROBOT_DATA)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_VERIFYDATA_WATERPROOF_ROBOT_DATA INCREMENT BY 1 START WITH 10000;

/*87*/
CREATE TABLE TB_ROBOT_POS_DATA
(



    CONSTRAINT ROBOT_POS_DATA_PK PRIMARY KEY (IDX_ROBOT_POS_DATA)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_ROBOT_POS_DATA INCREMENT BY 1 START WITH 10000;

/*88*/
CREATE TABLE TB_ROBOT_FALL_TEST
(



    CONSTRAINT ROBOT_FALL_TEST_PK PRIMARY KEY (IDX_ROBOT_FALL_TEST)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_ROBOT_FALL_TEST INCREMENT BY 1 START WITH 10000;

/*89*/
CREATE TABLE TB_ROBOT_NET_TEST
(



    CONSTRAINT ROBOT_NET_TEST_PK PRIMARY KEY (IDX_ROBOT_NET_TEST)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_ROBOT_NET_TEST INCREMENT BY 1 START WITH 10000;

/*90*/
CREATE TABLE TB_ROBOT_CAPA_TEST
(



    CONSTRAINT ROBOT_CAPA_TEST_PK PRIMARY KEY (IDX_ROBOT_CAPA_TEST)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_ROBOT_CAPA_TEST INCREMENT BY 1 START WITH 10000;

/*91*/
CREATE TABLE TB_ENV_GREENHOUSE_DATA
(



    CONSTRAINT ENV_GREENHOUSE_DATA_PK PRIMARY KEY (IDX_ENV_GREENHOUSE_DATA)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_ENV_GREENHOUSE_DATA INCREMENT BY 1 START WITH 10000;












/*91*/
CREATE TABLE TB_DEMO_BS_MSG
(
    IDX_DEMO_BS_MSG	NUMBER(32),
    MSG_TYPE	NUMBER(4) DEFAULT 1,
    MSG_CONTENTS	VARCHAR2(400),
    MSG_CODE	NUMBER(4) DEFAULT 0,
    NEED_UPLOAD_FILE	NUMBER(4) DEFAULT 0,
    UPLOAD_FILE_TYPE	NUMBER(4) DEFAULT 0,
    IS_FILE	NUMBER(4),
    DOWN_FILE_TYPE	NUMBER(4) DEFAULT 0,
    IDX_FILE	NUMBER(32) DEFAULT 0,
    IS_CUR	NUMBER(4) DEFAULT 0,
    IDX_USER_DEMO_BS	NUMBER(32) DEFAULT 0,
    IDX_ADMIN	NUMBER(32),
    REG_DATE	DATE,
    CONSTRAINT DEMO_BS_MSG_PK PRIMARY KEY (IDX_DEMO_BS_MSG)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_DEMO_BS_MSG INCREMENT BY 1 START WITH 10000;

/*91*/
CREATE TABLE TB_APPLICANT_DEMO_BS_JOIN
(
    IDX_APPLICANT_DEMO_BS_JOIN	NUMBER(32),
    APPLICANT_TYPE	NUMBER(4) DEFAULT 1,
    IDX_USER_DEMO_BS	NUMBER(32) DEFAULT 0,
    IDX_USER	NUMBER(32),
    JOIN_TYPE	NUMBER(4),
    REG_DATE	DATE,
    CONSTRAINT APPLICANT_DEMO_BS_JOIN_PK PRIMARY KEY (IDX_APPLICANT_DEMO_BS_JOIN)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_APPLICANT_DEMO_BS_JOIN INCREMENT BY 1 START WITH 10000;

CREATE TABLE TB_USER_DEMO_BS_DETAIL
(
    IDX_USER_DEMO_BS_DETAIL	NUMBER(32),
        IDX_USER_DEMO_BS	NUMBER(32),
        CEO_RND_RESULT1	VARCHAR2(100),
        CEO_RND_RESULT1_ORG	VARCHAR2(40),
        CEO_RND_RESULT1_DUR	VARCHAR2(40),
        CEO_RND_RESULT1_ROLE	VARCHAR2(40),
        CEO_RND_RESULT1_RESULT	VARCHAR2(100),
        CEO_RND_RESULT2	VARCHAR2 (100),
        CEO_RND_RESULT2_ORG	VARCHAR2(40),
        CEO_RND_RESULT2_DUR	VARCHAR2(40),
        CEO_RND_RESULT2_ROLE	VARCHAR2(40),
        CEO_RND_RESULT2_RESULT	VARCHAR2(100),
        RND_EFFORT1	VARCHAR2(200),
        RND_EFFORT1_TYPE	NUMBER(4),
        RND_EFFORT1_ETC	VARCHAR2(40),
        RND_EFFORT2	VARCHAR2(200),
        RND_EFFORT2_TYPE	NUMBER(4),
        RND_EFFORT2_ETC	VARCHAR2(40),
        RND_EFFORT3	VARCHAR2(200),
        RND_EFFORT3_TYPE	NUMBER(4),
        RND_EFFORT3_ETC	VARCHAR2(40),
        RND_EFFORT4	VARCHAR2(200),
        RND_EFFORT4_TYPE	NUMBER(4),
        RND_EFFORT4_ETC	VARCHAR2(40),
        RND_EFFORT5	VARCHAR2(200),
        RND_EFFORT5_TYPE	NUMBER(4),
        RND_EFFORT5_ETC	VARCHAR2(40),
        RND_EFFORT6	VARCHAR2(200),
        RND_EFFORT6_TYPE	NUMBER(4),
        RND_EFFORT6_ETC	VARCHAR2(40),
        OWN_IP1	VARCHAR2(100),
        OWN_IP1_TYPE	VARCHAR2(40),
        OWN_IP1_CODE	VARCHAR2(40),
        OWN_IP1_DATE	VARCHAR2(40),
        OWN_IP1_ORG	VARCHAR2(40),
        OWN_IP1_ETC	VARCHAR2(40),
        OWN_IP2	VARCHAR2(100),
        OWN_IP2_TYPE	VARCHAR2(40),
        OWN_IP2_CODE	VARCHAR2(40),
        OWN_IP2_DATE	VARCHAR2(40),
        OWN_IP2_ORG	VARCHAR2(40),
        OWN_IP2_ETC	VARCHAR2(40),
        OWN_IP3	VARCHAR2(100),
        OWN_IP3_TYPE	VARCHAR2(40),
        OWN_IP3_CODE	VARCHAR2(40),
        OWN_IP3_DATE	VARCHAR2(40),
        OWN_IP3_ORG	VARCHAR2(40),
        OWN_IP3_ETC	VARCHAR2(40),
        OWN_CERT1	VARCHAR2(100),
        OWN_CERT1_TYPE	VARCHAR2(40),
        OWN_CERT1_CODE	VARCHAR2(40),
        OWN_CERT1_DATE	VARCHAR2(40),
        OWN_CERT2	VARCHAR2(100),
        OWN_CERT2_TYPE	VARCHAR2(40),
        OWN_CERT2_CODE	VARCHAR2(40),
        OWN_CERT2_DATE	VARCHAR2(40),
        OWN_CERT3	VARCHAR2(100),
        OWN_CERT3_TYPE	VARCHAR2(40),
        OWN_CERT3_CODE	VARCHAR2(40),
        OWN_CERT3_DATE	VARCHAR2(40),
        OWN_DEVICE1	VARCHAR2(100),
        OWN_DEVICE1_WEIGHT	VARCHAR2(40),
        OWN_DEVICE1_SIZE	VARCHAR2(40),
        OWN_DEVICE1_PW	VARCHAR2(10),
        OWN_DEVICE1_WAT	VARCHAR2(10),
        OWN_DEVICE1_TYPE	VARCHAR2(10),
        IS_IN_OWN_DEVICE1	NUMBER(4),
        OWN_DEVICE2	VARCHAR2(100),
        OWN_DEVICE2_WEIGHT	VARCHAR2(40),
        OWN_DEVICE2_SIZE	VARCHAR2(40),
        OWN_DEVICE2_PW	VARCHAR2(10),
        OWN_DEVICE2_WAT	VARCHAR2(10),
        OWN_DEVICE2_TYPE	VARCHAR2(10),
        IS_IN_OWN_DEVICE2	NUMBER(4),
        OWN_DEVICE3	VARCHAR2(100),
        OWN_DEVICE3_WEIGHT	VARCHAR2(40),
        OWN_DEVICE3_SIZE	VARCHAR2(40),
        OWN_DEVICE3_PW	VARCHAR2(10),
        OWN_DEVICE3_WAT	VARCHAR2(10),
        OWN_DEVICE3_TYPE	VARCHAR2(10),
        IS_IN_OWN_DEVICE3	NUMBER(4),
        DEMO_NEEDS	VARCHAR2(3000),
        DEMO_MAIN_POINT	VARCHAR2(3000),
        DEMO_USE_PLAN	VARCHAR2(3000),
        DEMO_FACIL_MAT	VARCHAR2(600),
        DEMO_FACIL_ICT	VARCHAR2(600),
        DEMO_FACIL_FER	VARCHAR2(600),
        DEMO_FACIL_SW	VARCHAR2(600),
        DEMO_FACIL_ROBOT	VARCHAR2(600),
        DEMO_FACIL_MODEL	VARCHAR2(600),
        DEMO_PALN_GH	VARCHAR2(3000),
        DEMO_PALN_FACIL	VARCHAR2(3000),
        DEMO_PALN_EXPER	VARCHAR2(3000),
        DEMO_PALN_MNG	VARCHAR2(3000),
        DEMO_PLAN_IP	VARCHAR2(3000),
        DEMO_PLAN_TARGET	VARCHAR2(3000),
        DEMO_PLAN_SALES	VARCHAR2(3000),
        DEMO_PLAN_POST	VARCHAR2(3000),
        IN_FACIL_MAT	VARCHAR2(40),
        IN_FACIL_MAT_TYPE	VARCHAR2(10),
        IN_FACIL_MAT_STNRD	VARCHAR2(10),
        IN_FACIL_MAT_AMOUNT	NUMBER(4),
        IN_FACIL_MAT_VAL	NUMBER(4),
        IN_FACIL_MAT_PRICE	NUMBER(10),
        IN_FACIL_ICT	VARCHAR2(40),
        IN_FACIL_ICT_TYPE	VARCHAR2(10),
        IN_FACIL_ICT_STNRD	VARCHAR2(10),
        IN_FACIL_ICT_AMOUNT	NUMBER(4),
        IN_FACIL_ICT_VAL	NUMBER(4),
        IN_FACIL_ICT_PRICE	NUMBER(10),
        IN_FACIL_FER	VARCHAR2(40),
        IN_FACIL_FER_TYPE	VARCHAR2(10),
        IN_FACIL_FER_STNRD	VARCHAR2(10),
        IN_FACIL_FER_AMOUNT	NUMBER(4),
        IN_FACIL_FER_VAL	NUMBER(4),
        IN_FACIL_FER_PRICE	NUMBER(10),
        IN_FACIL_SW	VARCHAR2(40),
        IN_FACIL_SW_TYPE	VARCHAR2(10),
        IN_FACIL_SW_STNRD	VARCHAR2(10),
        IN_FACIL_SW_AMOUNT	NUMBER(4),
        IN_FACIL_SW_VAL	NUMBER(4),
        IN_FACIL_SW_PRICE	NUMBER(10),
        IN_FACIL_SEEDING	VARCHAR2(40),
        IN_FACIL_SEEDINGTYPE	VARCHAR2(10),
        IN_FACIL_SEEDING_STNRD	VARCHAR2(10),
        IN_FACIL_SEEDING_AMOUNT	NUMBER(4),
        IN_FACIL_SEEDING_VAL	NUMBER(4),
        IN_FACIL_SEEDING_PRICE	NUMBER(10),
        IN_FACIL_ROBOT	VARCHAR2(40),
        IN_FACIL_ROBOT_TYPE	VARCHAR2(10),
        IN_FACIL_ROBOT_STNRD	VARCHAR2(10),
        IN_FACIL_ROBOT_AMOUNT	NUMBER(4),
        IN_FACIL_ROBOT_VAL	NUMBER(4),
        IN_FACIL_ROBOT_PRICE	NUMBER(10),
        IN_HAZD_CHEMICAL1	VARCHAR2(40),
        IN_HAZD_CHEMICAL1_FORM	VARCHAR2(20),
        IN_HAZD_CHEMICAL1_AMOUNT	VARCHAR2(20),
        IN_HAZD_CHEMICAL1_CASE	VARCHAR2(20),
        IN_HAZD_CHEMICAL1_LOC	VARCHAR2(20),
        IN_HAZD_CHEMICAL1_ETC	VARCHAR2(40),
        IN_HAZD_CHEMICAL2	VARCHAR2(40),
        IN_HAZD_CHEMICAL2_FORM	VARCHAR2(20),
        IN_HAZD_CHEMICAL2_AMOUNT	VARCHAR2(20),
        IN_HAZD_CHEMICAL2_CASE	VARCHAR2(20),
        IN_HAZD_CHEMICAL2_LOC	VARCHAR2(20),
        IN_HAZD_CHEMICAL2_ETC	VARCHAR2(40),
        IN_HAZD_CHEMICAL3	VARCHAR2(40),
        IN_HAZD_CHEMICAL3_FORM	VARCHAR2(20),
        IN_HAZD_CHEMICAL3_AMOUNT	VARCHAR2(20),
        IN_HAZD_CHEMICAL3_CASE	VARCHAR2(20),
        IN_HAZD_CHEMICAL3_LOC	VARCHAR2(20),
        IN_HAZD_CHEMICAL3_ETC	VARCHAR2(40),
        WASTE_WATER_AMOUNT	VARCHAR2(20),
        WASTE_WATER_CASE	VARCHAR2(20),
        WASTE_WATER_EXT_PLAN	VARCHAR2(100),
        WASTE_SOIL_AMOUNT	VARCHAR2(20),
        WASTE_SOIL_CASE	VARCHAR2(20),
        WASTE_SOIL_EXT_PLAN	VARCHAR2(100),
        FACIL_PW1	VARCHAR2(100),
        FACIL_PW1_TYPE	VARCHAR2(20),
        FACIL_PW1_V	VARCHAR2(10),
        FACIL_PW1_W	VARCHAR2(10),
        FACIL_PW2	VARCHAR2(100),
        FACIL_PW2_TYPE	VARCHAR2(20),
        FACIL_PW2_V	VARCHAR2(10),
        FACIL_PW2_W	VARCHAR2(10),
        FACIL_PW3	VARCHAR2(100),
        FACIL_PW3_TYPE	VARCHAR2(20),
        FACIL_PW3_V	VARCHAR2(10),
        FACIL_PW3_W	VARCHAR2(10),

    REG_DATE	DATE,
    UPD_DATE  DATE,
    CONSTRAINT USER_DEMO_BS_DETAIL_PK PRIMARY KEY (IDX_USER_DEMO_BS_DETAIL)
    )
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_USER_DEMO_BS_DETAIL INCREMENT BY 1 START WITH 10000;



CREATE TABLE TB_USER_BS_HUMAN_RESOURCE
(
IDX_USER_BS_HUMAN_RESOURCE	NUMBER(32),
IDX_USER_DEMO_BS	NUMBER(32),
RND_USER_ORDER	NUMBER(4),
RND_USER_NAME	VARCHAR2(20),
RND_USER_ROLE	VARCHAR2(20),
RND_USER_CODE	VARCHAR2(40),
RND_USER_BIRTH	VARCHAR2(20),
RND_USER_GRAD	VARCHAR2(40),
RND_USER_COL	VARCHAR2(40),
RND_USER_SCHOOL	VARCHAR2(40),
RND_USER_COL_DATE	VARCHAR2(20),
RND_USER_COL_PART	VARCHAR2(20),
RND_USER_6T	VARCHAR2(40),
RND_USER_RESULT	VARCHAR2(100),
REG_DATE	DATE,
LAST_UPD_DATE	DATE,
    CONSTRAINT USER_BS_HUMAN_RESOURCE_PK PRIMARY KEY (IDX_USER_BS_HUMAN_RESOURCE)
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    NOPARALLEL
    MONITORING;
CREATE SEQUENCE SEQ_USER_BS_HUMAN_RESOURCE INCREMENT BY 1 START WITH 10000;
