SELECT *
FROM (
         SELECT ROW_NUMBER() OVER(ORDER by POSTING_START_DATE DESC) AS ROW_NUM
              ,IDX_BS_ANNOUNCEMENT
              , ANNOUNCE_NUM
              , SUBJECT
              , ANNOUNCE_STATUS
              , IS_FILE
              , IS_NEW
              , AUTHOR
              , POSTING_START_DATE
              , VIEW_COUNT
         FROM (
                  SELECT * FROM TB_BS_ANNOUNCEMENT WHERE IS_SHOW=1
                                                AND POSTING_START_DATE <= SYSDATE AND POSTING_END_DATE >= SYSDATE
              ) WHERE ROWNUM <=10
     ) WHERE ROW_NUM >0

SELECT TO_CHAR( TRUNC(SYSDATE,'year')+1,'YYYY-MM-DD HH24:MI:SS') FROM DUAL;

SELECT TO_CHAR(SYSDATE,'YYYY')||'-01-01 00:00:00' FROM DUAL;
SELECT TO_CHAR(SYSDATE,'YYYY')||'-12-31 23:59:59' FROM DUAL;

SELECT TO_CHAR(TRUNC(SYSDATE,'YYYY'),'YYYY-MM-DD') FROM DUAL;


SELECT * FROM TB_SCHEDULE_ITEM WHERE IDX_ADMIN = 0  OR  IDX_ADMIN = 0
SELECT * FROM TB_SCHEDULE_ITEM WHERE (IDX_ADMIN = 1 OR  IDX_ADMIN = 0) AND START_DATE BETWEEN TO_DATE( SYSDATE-5,'YYYY-MM-DD HH24:MI:SS') AND TO_DATE( SYSDATE+124,'YYYY-MM-DD HH24:MI:SS')+0.999999;

SELECT TO_DATE(TO_CHAR(LEVEL, '000'), 'DDD') FROM DUAL CONNECT BY LEVEL <= TO_NUMBER(TO_CHAR(TO_DATE('12-31', 'MM-DD'), 'DDD'));

SELECT * FROM TB_SCHEDULE_ITEM WHERE IDX_ADMIN = 1  OR  IDX_ADMIN = 0 AND START_DATE BETWEEN TO_DATE('01-01', 'MM-DD') AND TO_DATE('12-31', 'MM-DD');


select
    *
from(
        select
            *
        from TB_ENV_DATA
        where (GUYOK, IDX_TB_ENV_DATA) in (
            select GUYOK, max(IDX_TB_ENV_DATA) as IDX_TB_ENV_DATA
            from TB_ENV_DATA A group by GUYOK
        )
        order by GUYOK ASC
    ) t
group by t.GUYOK

SELECT
    *
FROM (
         SELECT ROW_NUMBER() OVER(ORDER by IDX_TB_ENV_DATA DESC) AS ROW_NUM
              ,A.*
         FROM (
                  SELECT * FROM TB_ENV_DATA
                  WHERE GUYOK=1

                  ORDER BY IDX_TB_ENV_DATA DESC
              ) A
         WHERE ROWNUM <=10
     )
WHERE ROW_NUM > 0


SELECT * FROM (
                  SELECT ROW_NUMBER() OVER(ORDER by IDX_SMS_TEMPLATE DESC) AS ROW_NUM
        ,A.*
FROM (
    SELECT
    *
    FROM TB_SMS_TEMPLATE
    ORDER BY IDX_SMS_TEMPLATE DESC
    ) A
WHERE ROWNUM <=10
    )
WHERE ROW_NUM > 0

SELECT * FROM(
    SELECT ROW_NUMBER() OVER(ORDER by SEND_DATE DESC) AS ROW_NUM,
    A.*
FROM(
        SELECT
            *
        FROM SDK_SMS_SEND
    ) A
WHERE ROWNUM <=10
    )
WHERE ROW_NUM > 0


SELECT (SELECT COUNT(*) FROM TB_ADMIN ) AS TOT_COUNT,
       (SELECT COUNT(*) FROM TB_ADMIN WHERE ADMIN_TYPE <  2)  AS CONSOLE_USER_COUNT,
                                          (SELECT COUNT(*) FROM TB_ADMIN WHERE ADMIN_TYPE <  8 AND  ADMIN_TYPE >=  2 )AS CONSOLE_ADMIN_COUNT,
                                          (SELECT COUNT(*) FROM TB_ADMIN WHERE ADMIN_TYPE < 16 AND  ADMIN_TYPE >=  8 ) AS ADMIN_USER_COUNT,
                                          (SELECT COUNT(*) FROM TB_ADMIN WHERE ADMIN_TYPE >= 16 ) AS SUPER_ADMIN_COUNT
           FROM TB_ADMIN WHERE ROWNUM = 1


SELECT
    *
FROM (
         SELECT ROW_NUMBER() OVER(ORDER by IDX_USER DESC) AS ROW_NUM,
        A.*
FROM (
    SELECT * FROM TB_USER
    WHERE USER_TYPE != 1
    ) A
WHERE ROWNUM <=10
    )
WHERE ROW_NUM > 0